# description of this workflow, can be anything you want
name: Package and release

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # gets entire git history, needed for automatic changelogs
      - name: Package and release
        uses: BigWigsMods/packager@v2
